version: '2'
services:
  postgres:
    image: postgres:12.7
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_DB=merrymaker
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres:/var/lib/postgresql/data
    command: ['-c', 'shared_buffers=1GB']
  redis:
    image: redis
    ports:
      - 6380:6379
  testRedis:
    image: redis
    ports:
      - 6379:6379


volumes:
  postgres:
    driver: local
