// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/target/mmk-ui-api/internal/core (interfaces: AlertRepository)
//
// Generated by this command:
//
//	mockgen -package=mocks -destination=alert_repository_mock.go github.com/target/mmk-ui-api/internal/core AlertRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	core "github.com/target/mmk-ui-api/internal/core"
	model "github.com/target/mmk-ui-api/internal/domain/model"
	gomock "go.uber.org/mock/gomock"
)

// MockAlertRepository is a mock of AlertRepository interface.
type MockAlertRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAlertRepositoryMockRecorder
	isgomock struct{}
}

// MockAlertRepositoryMockRecorder is the mock recorder for MockAlertRepository.
type MockAlertRepositoryMockRecorder struct {
	mock *MockAlertRepository
}

// NewMockAlertRepository creates a new mock instance.
func NewMockAlertRepository(ctrl *gomock.Controller) *MockAlertRepository {
	mock := &MockAlertRepository{ctrl: ctrl}
	mock.recorder = &MockAlertRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAlertRepository) EXPECT() *MockAlertRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAlertRepository) Create(ctx context.Context, req *model.CreateAlertRequest) (*model.Alert, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(*model.Alert)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockAlertRepositoryMockRecorder) Create(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAlertRepository)(nil).Create), ctx, req)
}

// Delete mocks base method.
func (m *MockAlertRepository) Delete(ctx context.Context, id string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockAlertRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAlertRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockAlertRepository) GetByID(ctx context.Context, id string) (*model.Alert, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*model.Alert)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockAlertRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockAlertRepository)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockAlertRepository) List(ctx context.Context, opts *model.AlertListOptions) ([]*model.Alert, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, opts)
	ret0, _ := ret[0].([]*model.Alert)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockAlertRepositoryMockRecorder) List(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockAlertRepository)(nil).List), ctx, opts)
}

// ListWithSiteNames mocks base method.
func (m *MockAlertRepository) ListWithSiteNames(ctx context.Context, opts *model.AlertListOptions) ([]*model.AlertWithSiteName, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWithSiteNames", ctx, opts)
	ret0, _ := ret[0].([]*model.AlertWithSiteName)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListWithSiteNames indicates an expected call of ListWithSiteNames.
func (mr *MockAlertRepositoryMockRecorder) ListWithSiteNames(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWithSiteNames", reflect.TypeOf((*MockAlertRepository)(nil).ListWithSiteNames), ctx, opts)
}

// Resolve mocks base method.
func (m *MockAlertRepository) Resolve(ctx context.Context, params core.ResolveAlertParams) (*model.Alert, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve", ctx, params)
	ret0, _ := ret[0].(*model.Alert)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Resolve indicates an expected call of Resolve.
func (mr *MockAlertRepositoryMockRecorder) Resolve(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MockAlertRepository)(nil).Resolve), ctx, params)
}

// UpdateDeliveryStatus mocks base method.
func (m *MockAlertRepository) UpdateDeliveryStatus(ctx context.Context, params core.UpdateAlertDeliveryStatusParams) (*model.Alert, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDeliveryStatus", ctx, params)
	ret0, _ := ret[0].(*model.Alert)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateDeliveryStatus indicates an expected call of UpdateDeliveryStatus.
func (mr *MockAlertRepositoryMockRecorder) UpdateDeliveryStatus(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDeliveryStatus", reflect.TypeOf((*MockAlertRepository)(nil).UpdateDeliveryStatus), ctx, params)
}

// Stats mocks base method.
func (m *MockAlertRepository) Stats(ctx context.Context, siteID *string) (*model.AlertStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stats", ctx, siteID)
	ret0, _ := ret[0].(*model.AlertStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stats indicates an expected call of Stats.
func (mr *MockAlertRepositoryMockRecorder) Stats(ctx, siteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stats", reflect.TypeOf((*MockAlertRepository)(nil).Stats), ctx, siteID)
}
