// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/target/mmk-ui-api/internal/core (interfaces: EventRepository)
//
// Generated by this command:
//
//	mockgen -package=mocks -destination=event_repository_mock.go github.com/target/mmk-ui-api/internal/core EventRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/target/mmk-ui-api/internal/domain/model"
	gomock "go.uber.org/mock/gomock"
)

// MockEventRepository is a mock of EventRepository interface.
type MockEventRepository struct {
	ctrl     *gomock.Controller
	recorder *MockEventRepositoryMockRecorder
	isgomock struct{}
}

// MockEventRepositoryMockRecorder is the mock recorder for MockEventRepository.
type MockEventRepositoryMockRecorder struct {
	mock *MockEventRepository
}

// NewMockEventRepository creates a new mock instance.
func NewMockEventRepository(ctrl *gomock.Controller) *MockEventRepository {
	mock := &MockEventRepository{ctrl: ctrl}
	mock.recorder = &MockEventRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventRepository) EXPECT() *MockEventRepositoryMockRecorder {
	return m.recorder
}

// BulkInsert mocks base method.
func (m *MockEventRepository) BulkInsert(ctx context.Context, req model.BulkEventRequest, process bool) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkInsert", ctx, req, process)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkInsert indicates an expected call of BulkInsert.
func (mr *MockEventRepositoryMockRecorder) BulkInsert(ctx, req, process any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkInsert", reflect.TypeOf((*MockEventRepository)(nil).BulkInsert), ctx, req, process)
}

// BulkInsertWithProcessingFlags mocks base method.
func (m *MockEventRepository) BulkInsertWithProcessingFlags(ctx context.Context, req model.BulkEventRequest, shouldProcessMap map[int]bool) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkInsertWithProcessingFlags", ctx, req, shouldProcessMap)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkInsertWithProcessingFlags indicates an expected call of BulkInsertWithProcessingFlags.
func (mr *MockEventRepositoryMockRecorder) BulkInsertWithProcessingFlags(ctx, req, shouldProcessMap any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkInsertWithProcessingFlags", reflect.TypeOf((*MockEventRepository)(nil).BulkInsertWithProcessingFlags), ctx, req, shouldProcessMap)
}

// CountByJob mocks base method.
func (m *MockEventRepository) CountByJob(ctx context.Context, opts model.EventListByJobOptions) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByJob", ctx, opts)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByJob indicates an expected call of CountByJob.
func (mr *MockEventRepositoryMockRecorder) CountByJob(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByJob", reflect.TypeOf((*MockEventRepository)(nil).CountByJob), ctx, opts)
}

// GetByIDs mocks base method.
func (m *MockEventRepository) GetByIDs(ctx context.Context, eventIDs []string) ([]*model.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDs", ctx, eventIDs)
	ret0, _ := ret[0].([]*model.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDs indicates an expected call of GetByIDs.
func (mr *MockEventRepositoryMockRecorder) GetByIDs(ctx, eventIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDs", reflect.TypeOf((*MockEventRepository)(nil).GetByIDs), ctx, eventIDs)
}

// ListByJob mocks base method.
func (m *MockEventRepository) ListByJob(ctx context.Context, opts model.EventListByJobOptions) (*model.EventListPage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByJob", ctx, opts)
	ret0, _ := ret[0].(*model.EventListPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByJob indicates an expected call of ListByJob.
func (mr *MockEventRepositoryMockRecorder) ListByJob(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByJob", reflect.TypeOf((*MockEventRepository)(nil).ListByJob), ctx, opts)
}

// MarkProcessedByIDs mocks base method.
func (m *MockEventRepository) MarkProcessedByIDs(ctx context.Context, eventIDs []string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkProcessedByIDs", ctx, eventIDs)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkProcessedByIDs indicates an expected call of MarkProcessedByIDs.
func (mr *MockEventRepositoryMockRecorder) MarkProcessedByIDs(ctx, eventIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkProcessedByIDs", reflect.TypeOf((*MockEventRepository)(nil).MarkProcessedByIDs), ctx, eventIDs)
}
