// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/target/mmk-ui-api/internal/core (interfaces: HTTPAlertSinkRepository)
//
// Generated by this command:
//
//	mockgen -package=mocks -destination=http_alert_sink_repository_mock.go github.com/target/mmk-ui-api/internal/core HTTPAlertSinkRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/target/mmk-ui-api/internal/domain/model"
	gomock "go.uber.org/mock/gomock"
)

// MockHTTPAlertSinkRepository is a mock of HTTPAlertSinkRepository interface.
type MockHTTPAlertSinkRepository struct {
	ctrl     *gomock.Controller
	recorder *MockHTTPAlertSinkRepositoryMockRecorder
	isgomock struct{}
}

// MockHTTPAlertSinkRepositoryMockRecorder is the mock recorder for MockHTTPAlertSinkRepository.
type MockHTTPAlertSinkRepositoryMockRecorder struct {
	mock *MockHTTPAlertSinkRepository
}

// NewMockHTTPAlertSinkRepository creates a new mock instance.
func NewMockHTTPAlertSinkRepository(ctrl *gomock.Controller) *MockHTTPAlertSinkRepository {
	mock := &MockHTTPAlertSinkRepository{ctrl: ctrl}
	mock.recorder = &MockHTTPAlertSinkRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHTTPAlertSinkRepository) EXPECT() *MockHTTPAlertSinkRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockHTTPAlertSinkRepository) Create(ctx context.Context, req *model.CreateHTTPAlertSinkRequest) (*model.HTTPAlertSink, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(*model.HTTPAlertSink)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockHTTPAlertSinkRepositoryMockRecorder) Create(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockHTTPAlertSinkRepository)(nil).Create), ctx, req)
}

// Delete mocks base method.
func (m *MockHTTPAlertSinkRepository) Delete(ctx context.Context, id string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockHTTPAlertSinkRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockHTTPAlertSinkRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockHTTPAlertSinkRepository) GetByID(ctx context.Context, id string) (*model.HTTPAlertSink, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*model.HTTPAlertSink)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockHTTPAlertSinkRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockHTTPAlertSinkRepository)(nil).GetByID), ctx, id)
}

// GetByName mocks base method.
func (m *MockHTTPAlertSinkRepository) GetByName(ctx context.Context, name string) (*model.HTTPAlertSink, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", ctx, name)
	ret0, _ := ret[0].(*model.HTTPAlertSink)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockHTTPAlertSinkRepositoryMockRecorder) GetByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockHTTPAlertSinkRepository)(nil).GetByName), ctx, name)
}

// List mocks base method.
func (m *MockHTTPAlertSinkRepository) List(ctx context.Context, limit, offset int) ([]*model.HTTPAlertSink, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, limit, offset)
	ret0, _ := ret[0].([]*model.HTTPAlertSink)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockHTTPAlertSinkRepositoryMockRecorder) List(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockHTTPAlertSinkRepository)(nil).List), ctx, limit, offset)
}

// Update mocks base method.
func (m *MockHTTPAlertSinkRepository) Update(ctx context.Context, id string, req *model.UpdateHTTPAlertSinkRequest) (*model.HTTPAlertSink, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, req)
	ret0, _ := ret[0].(*model.HTTPAlertSink)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockHTTPAlertSinkRepositoryMockRecorder) Update(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockHTTPAlertSinkRepository)(nil).Update), ctx, id, req)
}
