// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/target/mmk-ui-api/internal/core (interfaces: JobRepository)
//
// Generated by this command:
//
//	mockgen -package=mocks -destination=job_repository_mock.go github.com/target/mmk-ui-api/internal/core JobRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	core "github.com/target/mmk-ui-api/internal/core"
	model "github.com/target/mmk-ui-api/internal/domain/model"
	gomock "go.uber.org/mock/gomock"
)

// MockJobRepository is a mock of JobRepository interface.
type MockJobRepository struct {
	ctrl     *gomock.Controller
	recorder *MockJobRepositoryMockRecorder
	isgomock struct{}
}

// MockJobRepositoryMockRecorder is the mock recorder for MockJobRepository.
type MockJobRepositoryMockRecorder struct {
	mock *MockJobRepository
}

// NewMockJobRepository creates a new mock instance.
func NewMockJobRepository(ctrl *gomock.Controller) *MockJobRepository {
	mock := &MockJobRepository{ctrl: ctrl}
	mock.recorder = &MockJobRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJobRepository) EXPECT() *MockJobRepositoryMockRecorder {
	return m.recorder
}

// Complete mocks base method.
func (m *MockJobRepository) Complete(ctx context.Context, id string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Complete", ctx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Complete indicates an expected call of Complete.
func (mr *MockJobRepositoryMockRecorder) Complete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Complete", reflect.TypeOf((*MockJobRepository)(nil).Complete), ctx, id)
}

// Create mocks base method.
func (m *MockJobRepository) Create(ctx context.Context, req *model.CreateJobRequest) (*model.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(*model.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockJobRepositoryMockRecorder) Create(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockJobRepository)(nil).Create), ctx, req)
}

// Delete mocks base method.
func (m *MockJobRepository) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockJobRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockJobRepository)(nil).Delete), ctx, id)
}

// DeleteByPayloadField mocks base method.
func (m *MockJobRepository) DeleteByPayloadField(ctx context.Context, params core.DeleteByPayloadFieldParams) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByPayloadField", ctx, params)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteByPayloadField indicates an expected call of DeleteByPayloadField.
func (mr *MockJobRepositoryMockRecorder) DeleteByPayloadField(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByPayloadField", reflect.TypeOf((*MockJobRepository)(nil).DeleteByPayloadField), ctx, params)
}

// Fail mocks base method.
func (m *MockJobRepository) Fail(ctx context.Context, id, errMsg string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Fail", ctx, id, errMsg)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Fail indicates an expected call of Fail.
func (mr *MockJobRepositoryMockRecorder) Fail(ctx, id, errMsg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fail", reflect.TypeOf((*MockJobRepository)(nil).Fail), ctx, id, errMsg)
}

// GetByID mocks base method.
func (m *MockJobRepository) GetByID(ctx context.Context, id string) (*model.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*model.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockJobRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockJobRepository)(nil).GetByID), ctx, id)
}

// Heartbeat mocks base method.
func (m *MockJobRepository) Heartbeat(ctx context.Context, jobID string, leaseSeconds int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Heartbeat", ctx, jobID, leaseSeconds)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Heartbeat indicates an expected call of Heartbeat.
func (mr *MockJobRepositoryMockRecorder) Heartbeat(ctx, jobID, leaseSeconds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Heartbeat", reflect.TypeOf((*MockJobRepository)(nil).Heartbeat), ctx, jobID, leaseSeconds)
}

// List mocks base method.
func (m *MockJobRepository) List(ctx context.Context, opts *model.JobListOptions) ([]*model.JobWithEventCount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, opts)
	ret0, _ := ret[0].([]*model.JobWithEventCount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockJobRepositoryMockRecorder) List(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockJobRepository)(nil).List), ctx, opts)
}

// ReserveNext mocks base method.
func (m *MockJobRepository) ReserveNext(ctx context.Context, jobType model.JobType, leaseSeconds int) (*model.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReserveNext", ctx, jobType, leaseSeconds)
	ret0, _ := ret[0].(*model.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReserveNext indicates an expected call of ReserveNext.
func (mr *MockJobRepositoryMockRecorder) ReserveNext(ctx, jobType, leaseSeconds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReserveNext", reflect.TypeOf((*MockJobRepository)(nil).ReserveNext), ctx, jobType, leaseSeconds)
}

// Stats mocks base method.
func (m *MockJobRepository) Stats(ctx context.Context, jobType model.JobType) (*model.JobStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stats", ctx, jobType)
	ret0, _ := ret[0].(*model.JobStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stats indicates an expected call of Stats.
func (mr *MockJobRepositoryMockRecorder) Stats(ctx, jobType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stats", reflect.TypeOf((*MockJobRepository)(nil).Stats), ctx, jobType)
}

// WaitForNotification mocks base method.
func (m *MockJobRepository) WaitForNotification(ctx context.Context, jobType model.JobType) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WaitForNotification", ctx, jobType)
	ret0, _ := ret[0].(error)
	return ret0
}

// WaitForNotification indicates an expected call of WaitForNotification.
func (mr *MockJobRepositoryMockRecorder) WaitForNotification(ctx, jobType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WaitForNotification", reflect.TypeOf((*MockJobRepository)(nil).WaitForNotification), ctx, jobType)
}
