// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/target/mmk-ui-api/internal/core (interfaces: JobIntrospector)
//
// Generated by this command:
//
//	mockgen -package=mocks -destination=job_introspector_mock.go github.com/target/mmk-ui-api/internal/core JobIntrospector
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	"github.com/target/mmk-ui-api/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockJobIntrospector is a mock of JobIntrospector interface.
type MockJobIntrospector struct {
	ctrl     *gomock.Controller
	recorder *MockJobIntrospectorMockRecorder
	isgomock struct{}
}

// MockJobIntrospectorMockRecorder is the mock recorder for MockJobIntrospector.
type MockJobIntrospectorMockRecorder struct {
	mock *MockJobIntrospector
}

// NewMockJobIntrospector creates a new mock instance.
func NewMockJobIntrospector(ctrl *gomock.Controller) *MockJobIntrospector {
	mock := &MockJobIntrospector{ctrl: ctrl}
	mock.recorder = &MockJobIntrospectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJobIntrospector) EXPECT() *MockJobIntrospectorMockRecorder {
	return m.recorder
}

// RunningJobExistsByTaskName mocks base method.
func (m *MockJobIntrospector) RunningJobExistsByTaskName(ctx context.Context, taskName string, now time.Time) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunningJobExistsByTaskName", ctx, taskName, now)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunningJobExistsByTaskName indicates an expected call of RunningJobExistsByTaskName.
func (mr *MockJobIntrospectorMockRecorder) RunningJobExistsByTaskName(ctx, taskName, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunningJobExistsByTaskName", reflect.TypeOf((*MockJobIntrospector)(nil).RunningJobExistsByTaskName), ctx, taskName, now)
}

// JobStatesByTaskName mocks base method.
func (m *MockJobIntrospector) JobStatesByTaskName(ctx context.Context, taskName string, now time.Time) (domain.OverrunStateMask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "JobStatesByTaskName", ctx, taskName, now)
	ret0, _ := ret[0].(domain.OverrunStateMask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// JobStatesByTaskName indicates an expected call of JobStatesByTaskName.
func (mr *MockJobIntrospectorMockRecorder) JobStatesByTaskName(ctx, taskName, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "JobStatesByTaskName", reflect.TypeOf((*MockJobIntrospector)(nil).JobStatesByTaskName), ctx, taskName, now)
}
