// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/target/mmk-ui-api/internal/core (interfaces: ScheduledJobsAdminRepository)
//
// Generated by this command:
//
//	mockgen -package=mocks -destination=scheduled_jobs_admin_repository_mock.go github.com/target/mmk-ui-api/internal/core ScheduledJobsAdminRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	"github.com/target/mmk-ui-api/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockScheduledJobsAdminRepository is a mock of ScheduledJobsAdminRepository interface.
type MockScheduledJobsAdminRepository struct {
	ctrl     *gomock.Controller
	recorder *MockScheduledJobsAdminRepositoryMockRecorder
	isgomock struct{}
}

// MockScheduledJobsAdminRepositoryMockRecorder is the mock recorder for MockScheduledJobsAdminRepository.
type MockScheduledJobsAdminRepositoryMockRecorder struct {
	mock *MockScheduledJobsAdminRepository
}

// NewMockScheduledJobsAdminRepository creates a new mock instance.
func NewMockScheduledJobsAdminRepository(ctrl *gomock.Controller) *MockScheduledJobsAdminRepository {
	mock := &MockScheduledJobsAdminRepository{ctrl: ctrl}
	mock.recorder = &MockScheduledJobsAdminRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScheduledJobsAdminRepository) EXPECT() *MockScheduledJobsAdminRepositoryMockRecorder {
	return m.recorder
}

// DeleteByTaskName mocks base method.
func (m *MockScheduledJobsAdminRepository) DeleteByTaskName(ctx context.Context, taskName string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByTaskName", ctx, taskName)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteByTaskName indicates an expected call of DeleteByTaskName.
func (mr *MockScheduledJobsAdminRepositoryMockRecorder) DeleteByTaskName(ctx, taskName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByTaskName", reflect.TypeOf((*MockScheduledJobsAdminRepository)(nil).DeleteByTaskName), ctx, taskName)
}

// UpsertByTaskName mocks base method.
func (m *MockScheduledJobsAdminRepository) UpsertByTaskName(ctx context.Context, req domain.UpsertTaskParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertByTaskName", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertByTaskName indicates an expected call of UpsertByTaskName.
func (mr *MockScheduledJobsAdminRepositoryMockRecorder) UpsertByTaskName(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertByTaskName", reflect.TypeOf((*MockScheduledJobsAdminRepository)(nil).UpsertByTaskName), ctx, req)
}
