// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/target/mmk-ui-api/internal/core (interfaces: SiteRepository)
//
// Generated by this command:
//
//	mockgen -package=mocks -destination=site_repository_mock.go github.com/target/mmk-ui-api/internal/core SiteRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/target/mmk-ui-api/internal/domain/model"
	gomock "go.uber.org/mock/gomock"
)

// MockSiteRepository is a mock of SiteRepository interface.
type MockSiteRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSiteRepositoryMockRecorder
	isgomock struct{}
}

// MockSiteRepositoryMockRecorder is the mock recorder for MockSiteRepository.
type MockSiteRepositoryMockRecorder struct {
	mock *MockSiteRepository
}

// NewMockSiteRepository creates a new mock instance.
func NewMockSiteRepository(ctrl *gomock.Controller) *MockSiteRepository {
	mock := &MockSiteRepository{ctrl: ctrl}
	mock.recorder = &MockSiteRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSiteRepository) EXPECT() *MockSiteRepositoryMockRecorder { return m.recorder }

// Create mocks base method.
func (m *MockSiteRepository) Create(ctx context.Context, req *model.CreateSiteRequest) (*model.Site, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(*model.Site)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockSiteRepositoryMockRecorder) Create(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSiteRepository)(nil).Create), ctx, req)
}

// GetByID mocks base method.
func (m *MockSiteRepository) GetByID(ctx context.Context, id string) (*model.Site, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*model.Site)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockSiteRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockSiteRepository)(nil).GetByID), ctx, id)
}

// GetByName mocks base method.
func (m *MockSiteRepository) GetByName(ctx context.Context, name string) (*model.Site, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", ctx, name)
	ret0, _ := ret[0].(*model.Site)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockSiteRepositoryMockRecorder) GetByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockSiteRepository)(nil).GetByName), ctx, name)
}

// List mocks base method.
func (m *MockSiteRepository) List(ctx context.Context, limit, offset int) ([]*model.Site, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, limit, offset)
	ret0, _ := ret[0].([]*model.Site)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockSiteRepositoryMockRecorder) List(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockSiteRepository)(nil).List), ctx, limit, offset)
}

// Update mocks base method.
func (m *MockSiteRepository) Update(ctx context.Context, id string, req model.UpdateSiteRequest) (*model.Site, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, req)
	ret0, _ := ret[0].(*model.Site)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockSiteRepositoryMockRecorder) Update(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSiteRepository)(nil).Update), ctx, id, req)
}

// Delete mocks base method.
func (m *MockSiteRepository) Delete(ctx context.Context, id string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockSiteRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSiteRepository)(nil).Delete), ctx, id)
}
